### ISSUE TITLE
 can someone u help me out

### ISSUE THREAD

**Issue by connonfodder** [Mastercard/masterpass-android-sample-app#1]
I'm an android developer from Singapore. can u tell me how to build the express checkout  in android? this example is app-to-app, I can not find another tutorial about app-to-web. waiting for your msg.

**Comment by oceanhuang** [comment]
Would this help? 

https://developer.mastercard.com/documentation/masterpass-merchant-integration#express-checkout

**Comment by connonfodder** [comment]
yeah, I read this before. but I finally find a answer [here](https://www.mastercard.com/mc_us/devzone/elearning/story.html).  the answer is I need a merchant account and a developer account, so I can got mobile sdk and some keys, the most important is full of information about how to build server and appliaction. Thanks a lot.
